/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Admin.Curso;
import Admin.CrearCurso;
import Admin.ActCurso;
import proyecto1.InicioSesion;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jaswl
 */
public class AdminCursos extends javax.swing.JFrame {

    
    public static Curso[] cursos = new Curso[100];
    public static int contCursos;

    // Para actualizar curso
    public static int fila;

    public static String codigo;
    public static String nombre;
    public static String creditos;
    public static String alumnos;
    public static String nomProfesor;
    /**
     * Creates new form AdminCursos
     */
    public AdminCursos() {
        initComponents();
       actualizarListaCursos();
       this.setResizable(false);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiarListaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CrearCursoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoCursos = new javax.swing.JTable();
        EliminarBtn = new javax.swing.JButton();
        ActualizarBtn = new javax.swing.JButton();
        CargaMBtn = new javax.swing.JButton();
        ExportarHTMLBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCursos = new javax.swing.JTable();
        CerrarSesinoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cambiarListaBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cambiarListaBtn.setText("Profesores");
        cambiarListaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarListaBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setText("Listado De Cursos");

        CrearCursoBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CrearCursoBtn.setText("Crear Curso");
        CrearCursoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCursoBtnActionPerformed(evt);
            }
        });

        ListadoCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Creditos", "Alumnos", "Profesor"
            }
        ));
        jScrollPane1.setViewportView(ListadoCursos);

        EliminarBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        ActualizarBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ActualizarBtn.setText("Actualizar");
        ActualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBtnActionPerformed(evt);
            }
        });

        CargaMBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CargaMBtn.setText("Carga Masiva");
        CargaMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaMBtnActionPerformed(evt);
            }
        });

        ExportarHTMLBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ExportarHTMLBtn.setText("Exportar Listado HTML");
        ExportarHTMLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarHTMLBtnActionPerformed(evt);
            }
        });

        TablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Puesto", "Curso", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(TablaCursos);

        CerrarSesinoBtn.setText("Cerrar Sesion");
        CerrarSesinoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesinoBtnRegresarBtn(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cambiarListaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(106, 106, 106)
                        .addComponent(CerrarSesinoBtn)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExportarHTMLBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CrearCursoBtn)
                                            .addComponent(EliminarBtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CargaMBtn)
                                            .addComponent(ActualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cambiarListaBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CerrarSesinoBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(EliminarBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CrearCursoBtn)
                                    .addComponent(ActualizarBtn))
                                .addGap(18, 18, 18)
                                .addComponent(CargaMBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(ExportarHTMLBtn)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarListaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarListaBtnActionPerformed
        AdminProfesor cambiaPestaña = new AdminProfesor();
        cambiaPestaña.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarListaBtnActionPerformed

    private void CrearCursoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCursoBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CrearCurso cc = new CrearCurso();
        cc.setVisible(true);
    }//GEN-LAST:event_CrearCursoBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        // TODO add your handling code here:
        fila = ListadoCursos.getSelectedRow();

        for (int i = fila; i < contCursos - 1; i++) {
            cursos[i] = cursos[i + 1];
        }
        contCursos--;
        actualizarListaCursos();
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void ActualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBtnActionPerformed
        // TODO add your handling code here:
        fila = ListadoCursos.getSelectedRow();

        codigo = ListadoCursos.getModel().getValueAt(fila, 0).toString();
        nombre = ListadoCursos.getModel().getValueAt(fila, 1).toString();
        creditos = ListadoCursos.getModel().getValueAt(fila, 2).toString();
        alumnos = ListadoCursos.getModel().getValueAt(fila, 3).toString();
        nomProfesor = ListadoCursos.getModel().getValueAt(fila, 4).toString();
        

        this.setVisible(false);
        ActCurso ac = new ActCurso();
        ac.setVisible(true);
        
    }//GEN-LAST:event_ActualizarBtnActionPerformed

    private void CargaMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaMBtnActionPerformed
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);

        String filePath = fc.getSelectedFile().getAbsolutePath();
        System.out.println(filePath);

        BufferedReader reader = null;
        String line = "";

        contCursos = 0;

        try {
            reader = new BufferedReader(new FileReader(filePath));
            int contadorFila = 0;
            while ((line = reader.readLine()) != null) {
                if (contadorFila > 0) {
                    String[] columnas = line.split(";");

                    int cantAlumnos = (int) Math.floor(Math.random() * (80 - 0) + 0);
                    Curso curso = new Curso(columnas[0], columnas[1],
                        columnas[2], String.valueOf(cantAlumnos), columnas[3]);

                    cursos[contadorFila - 1] = curso;

                }
                contadorFila++;

            }
            contCursos = contadorFila - 1;
            System.out.println(Arrays.toString(cursos));
            actualizarListaCursos();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CargaMBtnActionPerformed

    private void ExportarHTMLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarHTMLBtnActionPerformed
        // TODO add your handling code here:
        // codigo nombre creditos alumnos profesor
        String cadenaHTML = "<!DOCTYPE html>\n"
        + "<html>\n"
        + "<body>\n"
        + "\n"
        + "<h1>Listado de Cursos</h1>\n"
        + "\n"
        + "<table style=\"margin:auto\">\n"
        + "    <tr>\n"
        + "      <th>Código</th>\n"
        + "      <th>Nombre</th>\n"
        + "      <th>Créditos</th>\n"
        + "      <th>Alumnos</th>\n"
        + "      <th>Profesor</th>\n"
        + "    </tr>";

        for (int i = 0; i < contCursos; i++) {
            cadenaHTML += "<tr>\n"
            + "<td>" + cursos[i].codigo + "</td>\n"
            + "<td>" + cursos[i].nombre + "</td>\n"
            + "<td>" + cursos[i].creditos + "</td>\n"
            + "<td>" + cursos[i].alumnos + "</td>\n"
            + "<td>" + cursos[i].nomProfesor + "</td>\n"
            + "</tr>";
        }

        cadenaHTML += "</table>\n"
        + "</body>\n"
        + "</html>\n";

        System.out.println(cadenaHTML);

        FileWriter fichero = null;
        PrintWriter pw = null;

        try{
            fichero = new FileWriter("./html/htmlCursos.html");
            pw = new PrintWriter(fichero);

            pw.println(cadenaHTML);
            fichero.close();
            //System.out.println(cadenaHTML);
        }catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ExportarHTMLBtnActionPerformed

    private void CerrarSesinoBtnRegresarBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesinoBtnRegresarBtn
        InicioSesion cambiaPestaña = new InicioSesion();
        cambiaPestaña.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesinoBtnRegresarBtn

    public void actualizarListaCursos() {

        if (contCursos > 0) {

            // actualizar listado
            DefaultTableModel modeloListado = (DefaultTableModel) ListadoCursos.getModel();
            modeloListado.setRowCount(contCursos);

            for (int i = 0; i < contCursos; i++) {
                modeloListado.setValueAt(cursos[i].codigo, i, 0);
                modeloListado.setValueAt(cursos[i].nombre, i, 1);
                modeloListado.setValueAt(cursos[i].creditos, i, 2);
                modeloListado.setValueAt(cursos[i].alumnos, i, 3);
                modeloListado.setValueAt(cursos[i].nomProfesor, i, 4);
            }

            // hacer top 3
            Curso[] arregloCopia = cursos.clone();

            // burbuja
            for (int comprobacion = 0; comprobacion < contCursos; comprobacion++) {
                System.out.println("Iniciando comprobacion");

                // ciclo para recorrer los elementos del arreglo
                for (int elementoArreglo = 0; elementoArreglo < contCursos - 1; elementoArreglo++) {
                    Curso elementoActual = arregloCopia[elementoArreglo];
                    Curso elementoSiguiente = arregloCopia[elementoArreglo + 1];

                    // si el actual es mayor al siguiente
                    if (Integer.valueOf(elementoActual.alumnos)
                            < Integer.valueOf(elementoSiguiente.alumnos)) {
                        // Se hace el intercambio
                        arregloCopia[elementoArreglo] = elementoSiguiente;
                        arregloCopia[elementoArreglo + 1] = elementoActual;

                    }
                }
            }

            System.out.println("entra aquii");
            // actualizar listado
            DefaultTableModel TablaCursosT3 = (DefaultTableModel) TablaCursos.getModel();

            TablaCursosT3.setValueAt("1", 0, 0);
            TablaCursosT3.setValueAt("2", 1, 0);
            TablaCursosT3.setValueAt("3", 2, 0);

            for (int i = 0; i < 3; i++) {
                // puesto, nombre, cantidad
                TablaCursos.setValueAt(arregloCopia[i].nombre, i, 1);
                TablaCursos.setValueAt(arregloCopia[i].alumnos, i, 2);
            }

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBtn;
    private javax.swing.JButton CargaMBtn;
    private javax.swing.JButton CerrarSesinoBtn;
    private javax.swing.JButton CrearCursoBtn;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JButton ExportarHTMLBtn;
    private javax.swing.JTable ListadoCursos;
    private javax.swing.JTable TablaCursos;
    private javax.swing.JButton cambiarListaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
