/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Admin.Profs;
import Admin.ActProfesor;
import proyecto1.InicioSesion;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JButton;
import Admin.Ventana;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 *
 * @author jaswl
 */
public class AdminProfesor extends javax.swing.JFrame {
    
    public static Profs[] profesores = new Profs[50];
    public static int contProfes;
    
    
    public static int fila;
        
        public static String nom;
        public static String apellido;
        public static String codigo;
        public static String correo;
        public static String contrasena;
        public static String genero;
        
        
    public AdminProfesor() {
        initComponents();
        actualizarListaProfes();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloProfesores = new javax.swing.JLabel();
        AddProfeBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        ActBtn = new javax.swing.JButton();
        htmlBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaGenero = new javax.swing.JTable();
        cambiarListaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoProfesores = new javax.swing.JTable();
        CerrarSesinoBtn = new javax.swing.JButton();
        CargaMBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));

        TituloProfesores.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TituloProfesores.setText("LISTA DE PROFESORES");

        AddProfeBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AddProfeBtn.setText("Agregar Profesor");
        AddProfeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfeBtnActionPerformed(evt);
            }
        });

        EliminarBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        ActBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ActBtn.setText("Actualizar");
        ActBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActBtnActionPerformed(evt);
            }
        });

        htmlBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        htmlBtn.setText("Exportar Listado a HTML");
        htmlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlBtnActionPerformed(evt);
            }
        });

        TablaGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Genero", "Porcentaje"
            }
        ));
        jScrollPane2.setViewportView(TablaGenero);

        cambiarListaBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cambiarListaBtn.setText("Cursos");
        cambiarListaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarListaBtnActionPerformed(evt);
            }
        });

        ListadoProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Correo", "Contrasena", "Genero"
            }
        ));
        jScrollPane1.setViewportView(ListadoProfesores);

        CerrarSesinoBtn.setText("Cerrar Sesion");
        CerrarSesinoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesinoBtnRegresarBtn(evt);
            }
        });

        CargaMBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CargaMBtn.setText("Carga Masiva");
        CargaMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaMBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EliminarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CargaMBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddProfeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(htmlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(TituloProfesores))
                    .addComponent(cambiarListaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarSesinoBtn)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(TituloProfesores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cambiarListaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CerrarSesinoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddProfeBtn)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EliminarBtn)
                            .addComponent(ActBtn)
                            .addComponent(CargaMBtn))
                        .addGap(44, 44, 44)
                        .addComponent(htmlBtn)
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddProfeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfeBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        crearProfesor cp = new crearProfesor();
        cp.setVisible(true);
    }//GEN-LAST:event_AddProfeBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        // TODO add your handling code here:
        fila = ListadoProfesores.getSelectedRow();
        
        for (int i = fila; i < contProfes - 1; i++){
        profesores[i] = profesores[i + 1];
    }
        contProfes--;
        actualizarListaProfes();
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void ActBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActBtnActionPerformed
        // TODO add your handling code here:
        fila = ListadoProfesores.getSelectedRow();

        codigo = ListadoProfesores.getModel().getValueAt(fila, 0).toString();
        nom = ListadoProfesores.getModel().getValueAt(fila, 1).toString();
        apellido = ListadoProfesores.getModel().getValueAt(fila, 2).toString();
        correo = ListadoProfesores.getModel().getValueAt(fila, 3).toString();
        contrasena = ListadoProfesores.getModel().getValueAt(fila, 4).toString();
        genero = ListadoProfesores.getModel().getValueAt(fila, 5).toString();

        this.setVisible(false);
        ActProfesor AP = new ActProfesor();
        AP.setVisible(true);
        
    }//GEN-LAST:event_ActBtnActionPerformed

    private void htmlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlBtnActionPerformed
        // TODO add your handling code here:
        String cadenaHTML = "<!DOCTYPE html>\n"
        + "<html>\n"
        + "<body>\n"
        + "\n"
        + "<h1>Listado de Profesores</h1>\n"
        + "\n"
        + "<table style=\"margin:auto\">\n"
        + "    <tr>\n"
        + "      <th>Código</th>\n"
        + "      <th>Nombre</th>\n"
        + "      <th>Apellido</th>\n"
        + "      <th>Correo</th>\n"
        + "      <th>Contraseña</th>\n"
        + "      <th>Género</th>\n"
        + "    </tr>";

        for (int i = 0; i < contProfes; i++) {
            cadenaHTML += "<tr>\n"
            + "<td>" + profesores[i].codigo + "</td>\n"
            + "<td>" + profesores[i].nom + "</td>\n"
            + "<td>" + profesores[i].apellido + "</td>\n"
            + "<td>" + profesores[i].correo + "</td>\n"
            + "<td>" + profesores[i].contrasena + "</td>\n"
            + "<td>" + profesores[i].genero + "</td>\n"
            + "</tr>";
        }

        cadenaHTML += "</table>\n"
        + "</body>\n"
        + "</html>\n";

        System.out.println(cadenaHTML);

        FileWriter fichero = null;
        PrintWriter pw = null;

        try{
            fichero = new FileWriter("./html/htmlProfesores.html");
            pw = new PrintWriter(fichero);

            pw.println(cadenaHTML);
            fichero.close();
            //System.out.println(cadenaHTML);
        }catch (Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_htmlBtnActionPerformed

    private void cambiarListaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarListaBtnActionPerformed
        AdminCursos cambiaPestaña = new AdminCursos();
        cambiaPestaña.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarListaBtnActionPerformed

    private void CerrarSesinoBtnRegresarBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesinoBtnRegresarBtn
        InicioSesion cambiaPestaña = new InicioSesion();
        cambiaPestaña.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesinoBtnRegresarBtn

    private void CargaMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaMBtnActionPerformed
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);

        String filePath = fc.getSelectedFile().getAbsolutePath();
        System.out.println(filePath);

        BufferedReader reader = null;
        String line = "";

        contProfes = 0;

        try {
            reader = new BufferedReader(new FileReader(filePath));
            int contadorFila = 0;
            while ((line = reader.readLine()) != null) {
                if (contadorFila > 0) {
                    String[] columnas = line.split(";");

                    Profs prof = new Profs(columnas[1], columnas[2],
                        columnas[0], columnas[3], "1234", columnas[4]);

                    profesores[contadorFila - 1] = prof;

                }
                contadorFila++;

            }
            contProfes = contadorFila - 1;
            System.out.println(Arrays.toString(profesores));
            actualizarListaProfes();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CargaMBtnActionPerformed

    
         public void actualizarListaProfes() {

        if (contProfes > 0) {

            // actualizar listado
            DefaultTableModel modeloListado = (DefaultTableModel) ListadoProfesores.getModel();
            modeloListado.setRowCount(contProfes);

            for (int i = 0; i < contProfes; i++) {
                modeloListado.setValueAt(profesores[i].codigo, i, 0);
                modeloListado.setValueAt(profesores[i].nom, i, 1);
                modeloListado.setValueAt(profesores[i].apellido, i, 2);
                modeloListado.setValueAt(profesores[i].correo, i, 3);
                modeloListado.setValueAt(profesores[i].contrasena, i, 4);
                modeloListado.setValueAt(profesores[i].genero, i, 5);
            }

            // contar generos
            int masculino = 0;
            int femenino = 0;

           /* for (int i = 0; i < contProfes; i++) {
                // si es hombre
                if (profesores[i].genero.equals("M")) {
                    masculino++;
                    // si es mujer
                } else {
                    femenino++;
                }
            }*/

            System.out.println(masculino);
            System.out.println(femenino);
            System.out.println(contProfes);

            System.out.println((double) (femenino / contProfes));

            // actualizar tabla
            DefaultTableModel modeloListadoG = (DefaultTableModel) TablaGenero.getModel();
            modeloListadoG.setValueAt("Femenino", 0, 0);
            modeloListadoG.setValueAt("Masculino", 1, 0);

            modeloListadoG.setValueAt((double) ((double) femenino / (double) contProfes) * 100, 0, 1);
            modeloListadoG.setValueAt((double) ((double) masculino / (double) contProfes) * 100, 1, 1);
        }
    }
         
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActBtn;
    private javax.swing.JButton AddProfeBtn;
    private javax.swing.JButton CargaMBtn;
    private javax.swing.JButton CerrarSesinoBtn;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JTable ListadoProfesores;
    private javax.swing.JTable TablaGenero;
    private javax.swing.JLabel TituloProfesores;
    private javax.swing.JButton cambiarListaBtn;
    private javax.swing.JButton htmlBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
